#!/bin/python3

import queue
from threading import Thread

#empty queue
q = queue.Queue()

#fill the queue
for i in range(100000):
    q.put(i)

#set thread num
num_threads = 8

#task to do
def do_stuff(thread_id):
    while True:
        print(thread_id)
        print(q.get())
        q.task_done()

#create threads as waiting deamons
for i in range(num_threads):
  worker = Thread(target=do_stuff, args=(i,))
  worker.setDaemon(True)
  worker.start()

#Blocks until all items in the queue have been gotten and processed.
q.join()
