#!/bin/bash

[ -z $1 ] && [ $# -eq 1 ] || echo "Usage = $0 <FILE_TO_SAVE>"

src_file=$1
abs_file=$(readlink -f ${file})
abs_dir=$(dirname ${file})
dst_dir="~/backup/$(date +%Y%m%dT%H%M)"/${abs_dir}

mkdir -p ${dst_dir} || echo "could not create ${dst_dir}"
cp ${abs_file} ${dst_dir}/. 
